/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TimedZoneDistribution } from './timedZoneDistribution';


export interface ActivityZone { 
    score?: number;
    distributionBuckets?: TimedZoneDistribution;
    type?: ActivityZone.TypeEnum;
    sensorBased?: boolean;
    points?: number;
    customZones?: boolean;
    max?: number;
}
export namespace ActivityZone {
    export type TypeEnum = 'heartrate' | 'power';
    export const TypeEnum = {
        Heartrate: 'heartrate' as TypeEnum,
        Power: 'power' as TypeEnum
    };
}
