/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * An enumeration of the types an activity may have.
 */
export type ActivityType = 'AlpineSki' | 'BackcountrySki' | 'Canoeing' | 'Crossfit' | 'EBikeRide' | 'Elliptical' | 'Golf' | 'Handcycle' | 'Hike' | 'IceSkate' | 'InlineSkate' | 'Kayaking' | 'Kitesurf' | 'NordicSki' | 'Ride' | 'RockClimbing' | 'RollerSki' | 'Rowing' | 'Run' | 'Sail' | 'Skateboard' | 'Snowboard' | 'Snowshoe' | 'Soccer' | 'StairStepper' | 'StandUpPaddling' | 'Surfing' | 'Swim' | 'Velomobile' | 'VirtualRide' | 'VirtualRun' | 'Walk' | 'WeightTraining' | 'Wheelchair' | 'Windsurf' | 'Workout' | 'Yoga';

export const ActivityType = {
    AlpineSki: 'AlpineSki' as ActivityType,
    BackcountrySki: 'BackcountrySki' as ActivityType,
    Canoeing: 'Canoeing' as ActivityType,
    Crossfit: 'Crossfit' as ActivityType,
    EBikeRide: 'EBikeRide' as ActivityType,
    Elliptical: 'Elliptical' as ActivityType,
    Golf: 'Golf' as ActivityType,
    Handcycle: 'Handcycle' as ActivityType,
    Hike: 'Hike' as ActivityType,
    IceSkate: 'IceSkate' as ActivityType,
    InlineSkate: 'InlineSkate' as ActivityType,
    Kayaking: 'Kayaking' as ActivityType,
    Kitesurf: 'Kitesurf' as ActivityType,
    NordicSki: 'NordicSki' as ActivityType,
    Ride: 'Ride' as ActivityType,
    RockClimbing: 'RockClimbing' as ActivityType,
    RollerSki: 'RollerSki' as ActivityType,
    Rowing: 'Rowing' as ActivityType,
    Run: 'Run' as ActivityType,
    Sail: 'Sail' as ActivityType,
    Skateboard: 'Skateboard' as ActivityType,
    Snowboard: 'Snowboard' as ActivityType,
    Snowshoe: 'Snowshoe' as ActivityType,
    Soccer: 'Soccer' as ActivityType,
    StairStepper: 'StairStepper' as ActivityType,
    StandUpPaddling: 'StandUpPaddling' as ActivityType,
    Surfing: 'Surfing' as ActivityType,
    Swim: 'Swim' as ActivityType,
    Velomobile: 'Velomobile' as ActivityType,
    VirtualRide: 'VirtualRide' as ActivityType,
    VirtualRun: 'VirtualRun' as ActivityType,
    Walk: 'Walk' as ActivityType,
    WeightTraining: 'WeightTraining' as ActivityType,
    Wheelchair: 'Wheelchair' as ActivityType,
    Windsurf: 'Windsurf' as ActivityType,
    Workout: 'Workout' as ActivityType,
    Yoga: 'Yoga' as ActivityType
};
