/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * A roll-up of metrics pertaining to a set of activities. Values are in seconds and meters.
 */
export interface ActivityTotal { 
    /**
     * The number of activities considered in this total.
     */
    count?: number;
    /**
     * The total distance covered by the considered activities.
     */
    distance?: number;
    /**
     * The total moving time of the considered activities.
     */
    movingTime?: number;
    /**
     * The total elapsed time of the considered activities.
     */
    elapsedTime?: number;
    /**
     * The total elevation gain of the considered activities.
     */
    elevationGain?: number;
    /**
     * The total number of achievements of the considered activities.
     */
    achievementCount?: number;
}
