/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BaseStream { 
    /**
     * The number of data points in this stream
     */
    originalSize?: number;
    /**
     * The level of detail (sampling) in which this stream was returned
     */
    resolution?: BaseStream.ResolutionEnum;
    /**
     * The base series used in the case the stream was downsampled
     */
    seriesType?: BaseStream.SeriesTypeEnum;
}
export namespace BaseStream {
    export type ResolutionEnum = 'low' | 'medium' | 'high';
    export const ResolutionEnum = {
        Low: 'low' as ResolutionEnum,
        Medium: 'medium' as ResolutionEnum,
        High: 'high' as ResolutionEnum
    };
    export type SeriesTypeEnum = 'distance' | 'time';
    export const SeriesTypeEnum = {
        Distance: 'distance' as SeriesTypeEnum,
        Time: 'time' as SeriesTypeEnum
    };
}
