/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SummaryAthlete } from './summaryAthlete';


export interface Comment { 
    /**
     * The unique identifier of this comment
     */
    id?: number;
    /**
     * The identifier of the activity this comment is related to
     */
    activityId?: number;
    /**
     * The content of the comment
     */
    text?: string;
    athlete?: SummaryAthlete;
    /**
     * The time at which this comment was created.
     */
    createdAt?: Date;
}
