/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SummaryGear } from './summaryGear';


export interface DetailedGear { 
    /**
     * The gear's unique identifier.
     */
    id?: string;
    /**
     * Resource state, indicates level of detail. Possible values: 2 -> \"summary\", 3 -> \"detail\"
     */
    resourceState?: number;
    /**
     * Whether this gear's is the owner's default one.
     */
    primary?: boolean;
    /**
     * The gear's name.
     */
    name?: string;
    /**
     * The distance logged with this gear.
     */
    distance?: number;
    /**
     * The gear's brand name.
     */
    brandName?: string;
    /**
     * The gear's model name.
     */
    modelName?: string;
    /**
     * The gear's frame type (bike only).
     */
    frameType?: number;
    /**
     * The gear's description.
     */
    description?: string;
}
