/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SummaryClub } from './summaryClub';


export interface DetailedClub { 
    /**
     * The club's unique identifier.
     */
    id?: number;
    /**
     * Resource state, indicates level of detail. Possible values: 1 -> \"meta\", 2 -> \"summary\", 3 -> \"detail\"
     */
    resourceState?: number;
    /**
     * The club's name.
     */
    name?: string;
    /**
     * URL to a 60x60 pixel profile picture.
     */
    profileMedium?: string;
    /**
     * URL to a ~1185x580 pixel cover photo.
     */
    coverPhoto?: string;
    /**
     * URL to a ~360x176  pixel cover photo.
     */
    coverPhotoSmall?: string;
    sportType?: DetailedClub.SportTypeEnum;
    /**
     * The club's city.
     */
    city?: string;
    /**
     * The club's state or geographical region.
     */
    state?: string;
    /**
     * The club's country.
     */
    country?: string;
    /**
     * Whether the club is private.
     */
    _private?: boolean;
    /**
     * The club's member count.
     */
    memberCount?: number;
    /**
     * Whether the club is featured or not.
     */
    featured?: boolean;
    /**
     * Whether the club is verified or not.
     */
    verified?: boolean;
    /**
     * The club's vanity URL.
     */
    url?: string;
    /**
     * The membership status of the logged-in athlete.
     */
    membership?: DetailedClub.MembershipEnum;
    /**
     * Whether the currently logged-in athlete is an administrator of this club.
     */
    admin?: boolean;
    /**
     * Whether the currently logged-in athlete is the owner of this club.
     */
    owner?: boolean;
    /**
     * The number of athletes in the club that the logged-in athlete follows.
     */
    followingCount?: number;
}
export namespace DetailedClub {
    export type SportTypeEnum = 'cycling' | 'running' | 'triathlon' | 'other';
    export const SportTypeEnum = {
        Cycling: 'cycling' as SportTypeEnum,
        Running: 'running' as SportTypeEnum,
        Triathlon: 'triathlon' as SportTypeEnum,
        Other: 'other' as SportTypeEnum
    };
    export type MembershipEnum = 'member' | 'pending';
    export const MembershipEnum = {
        Member: 'member' as MembershipEnum,
        Pending: 'pending' as MembershipEnum
    };
}
