/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LatLng } from './latLng';


export interface ExplorerSegment { 
    /**
     * The unique identifier of this segment
     */
    id?: number;
    /**
     * The name of this segment
     */
    name?: string;
    /**
     * The category of the climb [0, 5]. Higher is harder ie. 5 is Hors catégorie, 0 is uncategorized in climb_category. If climb_category = 5, climb_category_desc = HC. If climb_category = 2, climb_category_desc = 3.
     */
    climbCategory?: number;
    /**
     * The description for the category of the climb
     */
    climbCategoryDesc?: ExplorerSegment.ClimbCategoryDescEnum;
    /**
     * The segment's average grade, in percents
     */
    avgGrade?: number;
    startLatlng?: LatLng;
    endLatlng?: LatLng;
    /**
     * The segments's evelation difference, in meters
     */
    elevDifference?: number;
    /**
     * The segment's distance, in meters
     */
    distance?: number;
    /**
     * The polyline of the segment
     */
    points?: string;
}
export namespace ExplorerSegment {
    export type ClimbCategoryDescEnum = 'NC' | '4' | '3' | '2' | '1' | 'HC';
    export const ClimbCategoryDescEnum = {
        NC: 'NC' as ClimbCategoryDescEnum,
        _4: '4' as ClimbCategoryDescEnum,
        _3: '3' as ClimbCategoryDescEnum,
        _2: '2' as ClimbCategoryDescEnum,
        _1: '1' as ClimbCategoryDescEnum,
        HC: 'HC' as ClimbCategoryDescEnum
    };
}
