/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ZoneRanges } from './zoneRanges';


export interface HeartRateZoneRanges { 
    /**
     * Whether the athlete has set their own custom heart rate zones
     */
    customZones?: boolean;
    zones?: ZoneRanges;
}
