/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseStream } from './baseStream';
import { LatLng } from './latLng';


export interface LatLngStream { 
    /**
     * The number of data points in this stream
     */
    originalSize?: number;
    /**
     * The level of detail (sampling) in which this stream was returned
     */
    resolution?: LatLngStream.ResolutionEnum;
    /**
     * The base series used in the case the stream was downsampled
     */
    seriesType?: LatLngStream.SeriesTypeEnum;
    /**
     * The sequence of lat/long values for this stream
     */
    data?: Array<LatLng>;
}
export namespace LatLngStream {
    export type ResolutionEnum = 'low' | 'medium' | 'high';
    export const ResolutionEnum = {
        Low: 'low' as ResolutionEnum,
        Medium: 'medium' as ResolutionEnum,
        High: 'high' as ResolutionEnum
    };
    export type SeriesTypeEnum = 'distance' | 'time';
    export const SeriesTypeEnum = {
        Distance: 'distance' as SeriesTypeEnum,
        Time: 'time' as SeriesTypeEnum
    };
}
