/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ModelError { 
    /**
     * The code associated with this error.
     */
    code?: string;
    /**
     * The specific field or aspect of the resource associated with this error.
     */
    field?: string;
    /**
     * The type of resource associated with this error.
     */
    resource?: string;
}
