/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface RouteDirection { 
    /**
     * The distance in the route at which the action applies
     */
    distance?: number;
    /**
     * The action of this direction
     */
    action?: number;
    name?: string;
}
