/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SegmentLeaderboardEntry } from './segmentLeaderboardEntry';


/**
 * A
 */
export interface SegmentLeaderboard { 
    /**
     * The total number of entries for this leaderboard
     */
    entryCount?: number;
    /**
     * Deprecated, use entry_count
     */
    effortCount?: number;
    komType?: SegmentLeaderboard.KomTypeEnum;
    entries?: Array<SegmentLeaderboardEntry>;
}
export namespace SegmentLeaderboard {
    export type KomTypeEnum = 'kom' | 'cr';
    export const KomTypeEnum = {
        Kom: 'kom' as KomTypeEnum,
        Cr: 'cr' as KomTypeEnum
    };
}
