/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AltitudeStream } from './altitudeStream';
import { CadenceStream } from './cadenceStream';
import { DistanceStream } from './distanceStream';
import { HeartrateStream } from './heartrateStream';
import { LatLngStream } from './latLngStream';
import { MovingStream } from './movingStream';
import { PowerStream } from './powerStream';
import { SmoothGradeStream } from './smoothGradeStream';
import { SmoothVelocityStream } from './smoothVelocityStream';
import { TemperatureStream } from './temperatureStream';
import { TimeStream } from './timeStream';


export interface StreamSet { 
    time?: TimeStream;
    distance?: DistanceStream;
    latlng?: LatLngStream;
    altitude?: AltitudeStream;
    velocitySmooth?: SmoothVelocityStream;
    heartrate?: HeartrateStream;
    cadence?: CadenceStream;
    watts?: PowerStream;
    temp?: TemperatureStream;
    moving?: MovingStream;
    gradeSmooth?: SmoothGradeStream;
}
