/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SummarySegmentEffort { 
    /**
     * The unique identifier of this effort
     */
    id?: number;
    /**
     * The effort's elapsed time
     */
    elapsedTime?: number;
    /**
     * The time at which the effort was started.
     */
    startDate?: Date;
    /**
     * The time at which the effort was started in the local timezone.
     */
    startDateLocal?: Date;
    /**
     * The effort's distance in meters
     */
    distance?: number;
    /**
     * Whether this effort is the current best on the leaderboard
     */
    isKom?: boolean;
}
