/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TimedZoneRange } from './timedZoneRange';


/**
 * Stores the exclusive ranges representing zones and the time spent in each.
 */
export interface TimedZoneDistribution extends Array<TimedZoneRange> { 
}
