/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActivityType } from './activityType';


export interface UpdatableActivity { 
    /**
     * Whether this activity is a commute
     */
    commute?: boolean;
    /**
     * Whether this activity was recorded on a training machine
     */
    trainer?: boolean;
    /**
     * The description of the activity
     */
    description?: string;
    /**
     * The name of the activity
     */
    name?: string;
    type?: ActivityType;
    /**
     * Identifier for the gear associated with the activity. ‘none’ clears gear from activity
     */
    gearId?: string;
}
