/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Upload { 
    /**
     * The unique identifier of the upload
     */
    id?: number;
    /**
     * The external identifier of the upload
     */
    externalId?: string;
    /**
     * The error associated with this upload
     */
    error?: string;
    /**
     * The status of this upload
     */
    status?: string;
    /**
     * The identifier of the activity this upload resulted into
     */
    activityId?: number;
}
